language: objective-c

before_script:
  # set the JAVA_HOME which is not set by default for OSX Travis-CI workers
  - export "JAVA_HOME=`/usr/libexec/java_home`"
  - sh download.sh 'http://download.macromedia.com/pub/flashplayer/installers/archive/fp_11.7.700.225_archive.zip'

script: mvn -q test -DflashPlayer.command=Flash\ Player\ Debugger.app/Contents/MacOS/Flash\ Player\ Debugger