language: objective-c

before_script:
  - export "JAVA_HOME=`/usr/libexec/java_home`"
  - sh download.sh 'http://download.macromedia.com/pub/flashplayer/installers/archive/fp_11.7.700.225_archive.zip'
script:
  - mvn package -DflashPlayer.command=Flash\ Player\ Debugger.app/Contents/MacOS/Flash\ Player\ Debugger
after_success:
  - mvn flexmojos:asdoc-report
  - mvn flexmojos:coverage-report
  - zip -r asdoc asdoc
  - zip -r coverage coverage
  - cp target/stream-*.*.*.swc target/site/stream.swc
deploy:
  provider: releases
  api_key:
    secure: 1ZloFQElw9KHlGQ3bxX31GE5fioGgjeiHfwrXb4ZDtMPCIdTlppHsvQPPE42dzUOpWWO1bSfrJPznxo33ddZZ3m7exiAlBEJoxNJQFDONso9nRJkSPhiNPZoB2V3X/AQrCA1/qZilIwm3iaxRMYJMAOg5dub1XCAz0BOyYsYcGeYVA3hWXP9FRhJgJUB8duSxM0y/ag4DiCe4Ckq0peXZXilZmVSERmWDZCFNrNRbDxuNIugAEFdIsN1jbyq/jNq3VkGkV/tlkfGUfPi9jb/1vxUQ6KRT/ApIbnZDmxIwF4f31J/7SlUsVB/rWbE5h2EBiD9wewsieY/kg88qyn1DjdEW2583wnY5tb94yHMRx8G2XGTo/yXPVyZkA7+Pi4u/bk6q8Gpw/KW1cCbEAEo3JzwgFZU+n2CAuKW7O0JVpcuYN9I4wypEKzyyFfAALoZXhJxQxcj4/vAbaoeDYZcSd44x4KHTn4hFCygrrrc60V+5qoVV0KrPTslSbK4pNDGweo3facMsb1qu7x3pokSrUc7/zaof1lzrvRPmYjcHqKX1BS2BncEJ3oGVqI6PJFFR2uPsC0+xRkaYULnTpJerYk1vV8zdWupMGSHDp0ffLwpxF6CzIXM91tj5w8pnfzL0Fq9p7dvcE+C1ewdfwH+4/GVg8kRV+3QcAwykPk1gwc=
  file:
    - target/stream.swc
    - target/site/coverage.zip
    - target/site/asdoc.zip
  skip_cleanup: true
  on:
    tags: true
