language: objective-c

before_script:
  # set the JAVA_HOME which is not set by default for OSX Travis-CI workers
  - export "JAVA_HOME=`/usr/libexec/java_home`"
  # Download and install a specific Flash Player from the Adobe Archives:
  # http://helpx.adobe.com/flash-player/kb/archived-flash-player-versions.html
  - sh getFpFromArchive.sh 'https://fpdownload.macromedia.com/pub/flashplayer/installers/archive/fp_18.0.0.241_archive.zip'

script: mvn test -DflashPlayer.command=Flash\ Player\ Debugger.app/Contents/MacOS/Flash\ Player\ Debugger